--MAGNITUDE EXPLORATION

--FIND TOTAL CUSTOMERS BY COUNTRY
SELECT
Country,
COUNT(Customer_Key) AS Total_Customers
FROM gold.dim_customer
GROUP BY Country
ORDER BY Total_Customers DESC
--FIND TOTAL CUSTOMERS BY GENDER
SELECT
Gender,
COUNT(Customer_Key) AS Total_Customers
FROM gold.dim_customer
GROUP BY Gender
ORDER BY Total_Customers DESC
--FIND TOTAL PRODUCTS BY CATEGORY
SELECT
Category,
COUNT(Product_Key) AS Total_Products
FROM gold.dim_products
GROUP BY Category
ORDER BY Total_Products DESC
--AVEGRAGE COSTS IN EACH CATEGORY
SELECT
Category,
AVG(Cost) AS Average_Cost
FROM gold.dim_products
GROUP BY Category
ORDER BY Average_Cost DESC 
--TOTAL REVENUE GENERATED FOR EACH CATEGORY
SELECT
p.Category,
SUM (f.Sales) AS Total_Revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.Product_Key = f.Product_Key
GROUP BY Category
ORDER BY Total_Revenue DESC
-- TOTAL REVENUE GENERATED BY EACH CUSTOMER
SELECT
c.Customer_Key,
c.First_Name + ' ' + c.Last_Name AS Customer_Name,
SUM (f.Sales) AS Total_Revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customer c
ON c.Customer_Key = f.Customer_Key
GROUP BY c.Customer_Key, c.First_Name, c.Last_Name
ORDER BY Total_Revenue DESC

--DISTRIBUTION OF SOLD ITEMS ACROSS COUTRIES
SELECT
c.Country,
SUM (f.Quantity) AS Total_Item_Sold
FROM gold.fact_sales f
LEFT JOIN gold.dim_customer c
ON c.Customer_Key = f.Customer_Key
GROUP BY c.Country
ORDER BY Total_Item_Sold DESC